# Let travis know the language it needs to run

language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coverage

# Command to run tests

script:
 
- coverage run -m unittest discover && coverage report

# Using this  command travis will build your system and get the coverage.
after_script:
  - coveralls


