/**
 * Politico
 * Politico enables citizens give their mandate to politicians running for different government offices   while building trust in the process through   transparency. [http://swagger.io](http://swagger.io) or on  [irc.freenode.net, #swagger](http://swagger.io/irc/). 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dbelio39@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class Category (
  id: Option[Long] = None,
  name: Option[String] = None
) extends ApiModel


